FROM python:3.7-slim-stretch as builder

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV http_proxy http://proxy-chain.intel.com:911
ENV https_proxy http://proxy-chain.intel.com:912

WORKDIR /usr/src/mservice

COPY requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

COPY . .