version: '3.7'

services:
  python:
    build: 
      context: ./
      args:
        - HTTP_PROXY=http://proxy-chain.intel.com:911
        - HTTPS_PROXY=http://proxy-chain.intel.com:912
      dockerfile: ./DockerFile
    command:  >
      sh -c "cd scores && python manage.py test && python manage.py runserver 0.0.0.0:8000" 
    ports:
      - 8000:8000
    expose:
      - 8000